OperationalError at /ar/login/
no such column: rental_adminuser.is_deleted
Request Method:	POST
Request URL:	http://bb82d6c6-b836-4e1b-9dcb-6d3b85c2a466-00-1n99m5hl2yhtl.sisko.replit.dev/ar/login/
Django Version:	5.2
Exception Type:	OperationalError
Exception Value:	
no such column: rental_adminuser.is_deleted
Exception Location:	/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py, line 360, in execute
Raised during:	rental.views.login_view
Python Executable:	/nix/store/wqhkxzzlaswkj3gimqign99sshvllcg6-python-wrapped-0.1.0/bin/python3
Python Version:	3.11.10
Python Path:	
['/home/runner/workspace',
 '/home/runner/workspace/.pythonlibs/bin',
 '/nix/store/lc7qv2ldzrs1aq3hbyzmbgvn0h2w26pl-sitecustomize/lib/python/site-packages',
 '/nix/store/dfg63lldbvcj207iyr9z0xw21d8ax02n-python3.11-pip-24.0/lib/python3.11/site-packages',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python311.zip',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/lib-dynload',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/site-packages',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/nix/store/wblvmd5y7izx0z10d1w7ga7zc4apjxmb-python3.11-setuptools-75.1.1/lib/python3.11/site-packages',
 '/home/runner/workspace']
Server time:	Thu, 15 May 2025 22:20:47 +0000
Traceback Switch to copy-and-paste view
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/utils.py, line 105, in _execute
                return self.cursor.execute(sql, params)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py, line 360, in execute
        return super().execute(query, params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
The above exception (no such column: rental_adminuser.is_deleted) was the direct cause of the following exception:
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py, line 55, in inner
                response = get_response(request)
                               ^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py, line 197, in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/home/runner/workspace/rental/views.py, line 371, in login_view
                    admin_profile = AdminUser.objects.get(user=user)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/db/models/manager.py, line 87, in manager_method
                return getattr(self.get_queryset(), name)(*args, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 